### PR TITLE
add SHT21-Arduino-Library

### PR DESCRIPTION
**Pull request by Hannes7eicher**
This PR adds the SHT21-Arduino-Library.

### CODE REVIEW

**Comment by V205Arduino** [comment]
I don’t see the DFrobot sgp40 in the list…..

**Comment by Hannes7eicher** [comment]
You are right, excuse the late reply. I added it [here](https://github.com/arduino/uno-r4-library-compatibility/pull/22).

**Comment by V205Arduino** [comment]
OK thanks!

**Comment by V205Arduino** [comment]
OK thanks!

**Pull request merged**
